### ISSUE TITLE
Unsupported event type: ObjectCreated:CompleteMultipartUpload

### ISSUE THREAD

**Issue by 3lpsy** [koel/koel-aws#5]
I am utilizing the aws/lambda architecture. When I bulk upload from the cli like:

```
$ aws s3 cp music/* s3://bucket-name/
```

I receive the following error in the lambda logs: "Unsupported event type: ObjectCreated:CompleteMultipartUpload".

I ended up using [this solution](https://github.com/aws/aws-cli/issues/946) using the s3api, however, it would nice to have the lambda function account for the multipart upload.

**Comment by alejandro-carstens** [comment]
Hi 3Ipsy, I had the same problem as you. Simply check for the event and allow it. 

`if (record.eventName === 'ObjectCreated:Put' || record.eventName === 'ObjectCreated:CompleteMultipartUpload') {
		return handlePut(bucket, key, cb);
	} else if (record.eventName === 'ObjectRemoved:Delete' || record.eventName === 'ObjectRemoved:DeleteMarkerCreated'){
		return handleDelete(bucket, key, cb);
}`

I already submitted a pull request solving the issue.
